version: '3.4'

services:
  web:
    image: cngzgr/rasot.cms
    ports:
      - "5001:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
     - mysql
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - redis
      - mysql


  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "001453"
      MYSQL_DATABASE: rasotdb
      MYSQL_USER: root
    volumes:
      - /e/docker/rasot/mysql:/var/lib/mysql
      - dbdata:/e/docker/rasot/mysql
    restart: always

  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always

volumes:
   dbdata:
